/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.*;
import java.awt.Color;
import java.awt.EventQueue;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.ResultSet;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JPasswordField;
import javax.swing.JTextField;
import javax.swing.border.EmptyBorder;
import model.*;
/**
 *
 * @author mfthrr
 */
public class Login extends javax.swing.JFrame {
    public static String currentUser;
    
    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        input_password_login = new javax.swing.JTextField();
        input_username_login = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        btn_login = new javax.swing.JButton();
        btn_SignUp = new javax.swing.JButton();
        Username_Login = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        input_password_login.setBackground(new java.awt.Color(234, 234, 234));
        input_password_login.setText("Password");
        input_password_login.setBorder(null);
        input_password_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input_password_loginActionPerformed(evt);
            }
        });
        getContentPane().add(input_password_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 540, 230, 23));

        input_username_login.setBackground(new java.awt.Color(234, 234, 234));
        input_username_login.setText("Username");
        input_username_login.setBorder(null);
        input_username_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input_username_loginActionPerformed(evt);
            }
        });
        getContentPane().add(input_username_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 490, 230, 30));

        jTextField3.setBackground(new java.awt.Color(234, 234, 234));
        jTextField3.setBorder(null);
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 490, 230, 30));

        btn_login.setBackground(new java.awt.Color(0,0,0,1));
        btn_login.setBorder(null);
        btn_login.setBorderPainted(false);
        btn_login.setContentAreaFilled(false);
        btn_login.setContentAreaFilled(false);
        btn_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_loginActionPerformed(evt);
            }
        });
        getContentPane().add(btn_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 599, 140, 30));

        btn_SignUp.setBackground(new java.awt.Color(0,0,0,1));
        btn_SignUp.setBorderPainted(false);
        btn_SignUp.setContentAreaFilled(false);
        btn_SignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SignUpActionPerformed(evt);
            }
        });
        getContentPane().add(btn_SignUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 640, 60, 20));

        Username_Login.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI_asset/Login.png"))); // NOI18N
        getContentPane().add(Username_Login, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void input_password_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input_password_loginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_input_password_loginActionPerformed

    private void input_username_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input_username_loginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_input_username_loginActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void btn_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_loginActionPerformed
        // TODO add your handling code here:
        String userName = input_username_login.getText();
        String password = input_password_login.getText();
        User usr = new User(userName,password);
        DatabaseManager oh = new DatabaseManager();
        currentUser = usr.getUsername();                

        if (oh.userLogin(usr.getUsername(), usr.getPassword())) {
            dispose();
            Home ah = new Home();
            ah.setTitle("Home");
            ah.setLocationRelativeTo(null);
            ah.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(btn_login, "Username & Password Tidak Sesuai 😭");
        }        
    }//GEN-LAST:event_btn_loginActionPerformed

    private void btn_SignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SignUpActionPerformed
        // TODO add your handling code here:
        dispose();
        signUp ah = new signUp();
        ah.setTitle("Welcome");
        ah.setLocationRelativeTo(null);
        ah.setVisible(true);

    }//GEN-LAST:event_btn_SignUpActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
            Login loginFrame = new Login();
            loginFrame.setVisible(true);
            loginFrame.setLocationRelativeTo(null);
        }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Username_Login;
    private javax.swing.JButton btn_SignUp;
    private javax.swing.JButton btn_login;
    private javax.swing.JTextField input_password_login;
    private javax.swing.JTextField input_username_login;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
