/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.*;
import java.awt.BorderLayout;
import java.sql.SQLException;
import java.sql.Timestamp;
import javax.swing.*;
import model.*;
import view.*;
import static view.Home.usr;

/**
 *
 * @author mfthrr
 */
public class NoteEdit extends javax.swing.JFrame {
    private static final long serialVersionUID = 1L;

    /**
     * Creates new form Home
     */
    public NoteEdit() {
        initComponents();
    }  
    DatabaseManager databaseManager;  
    String judul;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_backHome = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        isi_Note = new javax.swing.JTextArea();
        input_title_note = new javax.swing.JTextField();
        btnEditNote = new javax.swing.JButton();
        Pesan = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_backHome.setBackground(new java.awt.Color(0,0,0,1));
        btn_backHome.setBorderPainted(false);
        btn_backHome.setContentAreaFilled(false);
        btn_backHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backHomeActionPerformed(evt);
            }
        });
        getContentPane().add(btn_backHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 30, 40));

        isi_Note.setBackground(new java.awt.Color(217, 217, 217));
        isi_Note.setColumns(20);
        isi_Note.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        isi_Note.setRows(5);
        isi_Note.setBorder(null);
        jScrollPane1.setViewportView(isi_Note);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 170, 320, 290));

        input_title_note.setBackground(null);
        input_title_note.setFont(new java.awt.Font("Dialog", 1, 22)); // NOI18N
        input_title_note.setForeground(new java.awt.Color(51, 51, 51));
        input_title_note.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        input_title_note.setText("Judul");
        input_title_note.setBorder(null);
        input_title_note.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input_title_noteActionPerformed(evt);
            }
        });
        getContentPane().add(input_title_note, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 220, 40));

        btnEditNote.setBorderPainted(false);
        btnEditNote.setContentAreaFilled(false);
        btnEditNote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditNoteActionPerformed(evt);
            }
        });
        getContentPane().add(btnEditNote, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 470, 70, 30));
        getContentPane().add(Pesan, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 560, 320, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI_asset/Note.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_backHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backHomeActionPerformed
        // TODO add your handling code here:       
        dispose();
        Home ah = new Home();
        ah.setTitle("Home");
        ah.setLocationRelativeTo(null);
        ah.setVisible(true);           
    }//GEN-LAST:event_btn_backHomeActionPerformed

    private void btnEditNoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditNoteActionPerformed
       try {
            DatabaseManager db = new DatabaseManager();
            String usernameEdit = usr; 
            Notes en = new Notes(input_title_note.getText(), isi_Note.getText());
            en.setUsername(usr);
            db.Edit(en, judul);
        } catch (SQLException e) {
            e.printStackTrace();
        } 
    }//GEN-LAST:event_btnEditNoteActionPerformed
    
    public void listData(Notes n) {
        judul = n.getJudul();
        input_title_note.setText(n.getJudul());
        isi_Note.setText(n.getIsi());
    }
      
    private void input_title_noteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input_title_noteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_input_title_noteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NoteEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NoteEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NoteEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NoteEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
            NoteEdit noteFrame = new NoteEdit();
            noteFrame.setVisible(true);
            noteFrame.setLocationRelativeTo(null);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Pesan;
    private javax.swing.JButton btnEditNote;
    private javax.swing.JButton btn_backHome;
    private javax.swing.JTextField input_title_note;
    private javax.swing.JTextArea isi_Note;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
