/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import model.*;
/**
 *
 * @author mfthrr
 */
public class signUp extends javax.swing.JFrame {

    /**
     * Creates new form signUp
     */
    public signUp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        input_username_signup = new javax.swing.JTextField();
        input_password1_signup = new javax.swing.JTextField();
        btn_signup = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        input_username_signup.setBackground(new java.awt.Color(234, 234, 234));
        input_username_signup.setText("Username");
        input_username_signup.setBorder(null);
        input_username_signup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input_username_signupActionPerformed(evt);
            }
        });
        getContentPane().add(input_username_signup, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 484, 230, 30));

        input_password1_signup.setBackground(new java.awt.Color(234, 234, 234));
        input_password1_signup.setText("Password");
        input_password1_signup.setBorder(null);
        input_password1_signup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input_password1_signupActionPerformed(evt);
            }
        });
        getContentPane().add(input_password1_signup, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 530, 230, 24));

        btn_signup.setBackground(new java.awt.Color(0,0,0,1)
        );
        btn_signup.setBorder(null);
        btn_signup.setContentAreaFilled(false);
        btn_signup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_signupActionPerformed(evt);
            }
        });
        getContentPane().add(btn_signup, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 600, 140, 30));

        jButton1.setBackground(new java.awt.Color(0,0,0,1));
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 640, 40, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI_asset/signUp.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void input_username_signupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input_username_signupActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_input_username_signupActionPerformed

    private void input_password1_signupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input_password1_signupActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_input_password1_signupActionPerformed

    private void btn_signupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_signupActionPerformed
        String newUserName = input_username_signup.getText();
        String newPassword = input_password1_signup.getText();
        
        User usr = new User(newUserName, newPassword);       
        DatabaseManager oh = new DatabaseManager();

        // Periksa apakah username atau password kosong
        if (usr.getUsername().trim().isEmpty() || usr.getPassword().trim().isEmpty()) {
            JOptionPane.showMessageDialog(btn_signup, "Username dan Password Tidak Boleh Kosong!");
            return; // Keluar dari metode jika username atau password kosong
        }
        // Panggil metode saveNewUser dari objek DatabaseManager
        if (oh.userSignup(usr.getUsername(), usr.getPassword())) {
            // Jika metode mengembalikan true, tampilkan pesan sukses dan buka Home
            dispose();
            Login ah = new Login();
            ah.setTitle("Selamat Datang");
            ah.setVisible(true);
            ah.setLocationRelativeTo(null);
            JOptionPane.showMessageDialog(btn_signup, "Anda Berhasil SignUp, Silahkan Login");
        } else {
            // Jika metode mengembalikan false, tampilkan pesan kesalahan spesifik
            JOptionPane.showMessageDialog(btn_signup, "Username Sudah Digunakan, Pilih Username Lain! 🙏");
        }
    }//GEN-LAST:event_btn_signupActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
                    dispose();
                    Login ah = new Login();
                    ah.setTitle("Welcome");
                    ah.setVisible(true); 
                    ah.setLocationRelativeTo(null);
    }//GEN-LAST:event_jButton1ActionPerformed
      
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(signUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(signUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(signUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(signUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            signUp signUpFrame = new signUp();
            signUpFrame.setVisible(true);
            signUpFrame.setLocationRelativeTo(null);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_signup;
    private javax.swing.JTextField input_password1_signup;
    private javax.swing.JTextField input_username_signup;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
